#include <iostream>

void foo() noexcept { std::cout << "This has no exception" << std::endl; }